### ISSUE TITLE
[Bug] D2Emu terror zone fetching is not working.

### ISSUE THREAD

**Issue by mrhappyasthma** [shupershuff/Diablo2RLoader#47] opened 2024-08-31 22:13 UTC
![image](https://github.com/user-attachments/assets/20156595-a76f-4672-a358-3c50b73d2cf0)

It just shows empty string. I tried `d2emu.com` and `D2Emu.com` in the config in case of capitalization issues.

**Comment by shupershuff** [comment] 2024-09-01 05:17
Thanks for posting the issue, was wondering when someone would do this :)

This is due to a very recent change in the D2Emu API now requiring a token (same issue as issue [48](https://github.com/shupershuff/Diablo2RLoader/issues/48)).
I've worked with the legend from D2Emu over the last couple days who has gone above and beyond to help me deploy a fix.

**"So where's the fix then?"**
I can't/won't make a formal release of this just yet as Microsoft are flagging the script as potentially malicious, probably due to API calls and regex used within the script. I think the new window reposition feature has also probably elevated it the perceived risk level as it relies on user32.dll to reposition windows.

I have made a submission for them to clear the false positive (again) but it might take a few days (took about a week for the v1.13.0 to be cleared).
If you do want to try out the new version (v1.13.2), you can manually grab this from the main repository, if windows defender flags it, you can manually copy the code and replace content of the old one.

**Comment by buggsi** [comment] 2024-09-01 21:25
Maybe it's time to port this tool to python. I was never a fan of PowerShell scripts.

**Comment by mrhappyasthma** [comment] 2024-09-02 00:45
+1 to rewriting. Idk powershell at all but I'm proficient at most standard programming languages. Perhaps we can rewrite in Python or Go or whatever. And just invoke shell commands where things can't be done natively in that language.

Would be easier to write unit tests too

**Comment by shupershuff** [comment] 2024-09-02 02:07
I am profficient in no programming languages lol. This project was in part a learning opportunity for me and to see how far I can push PowerShell to do things.

Feel free to give it a crack if you want to port to another language. I can assist with any Q&A around logic.

**Comment by mrhappyasthma** [comment] 2024-09-02 02:08
Awesome, maybe I'll take a stab at that on a branch

**Comment by buggsi** [comment] 2024-09-02 04:13
> I am profficient in no programming languages lol. This project was in part a learning opportunity for me and to see how far I can push PowerShell to do things.
> 
> Feel free to give it a crack if you want to port to another language. I can assist with any Q&A around logic.

It's quite a feat you pulled it off, PowerShell is so complicated and convoluted, it's gross. Your script is insanely big, when it can be only a few kilobytes in python, and slightly more in nodejs.

**Comment by shupershuff** [comment] 2024-09-02 07:32
@mrhappyasthma @buggsi if either of you manually downloaded the pre-release version from the main branch, I'd recommend you redownload it. Just made a new release for v1.13.2.

Closing as the issue is now resolved.

**Closed by shupershuff** 2024-09-02 07:32 UTC
